#!/usr/bin/env bash

## templates/engine/game-base ##
## This template provides the backbone for each gameserver game
##
## What this enables is a consistent, streamlined experience for both developing
##   and using the game server
## Games are rendered from Game objects in python created from <game>.json files
##   in static/games/configs/
##
## Author: Daniel Tucker <github.com/Vision940>
##

# Source actual game implementation
__gs_source_file {{ game.source_name }} static/games/{{ game.source_name }}
if ! declare -f __gs_{{ game.cmd_name }}_main &>/dev/null && {{ game.has_main | lower}}; then
  __gs_errormsg "Could not source {{ game.cmd_name }} - main function not found in static/games/{{ game.cmd_name }}"
  return
fi

GS_{{ game.cmd_name | upper | replace('-', '_') }}_VERSION={{ game.version }}

# Source game imports
__gs_{{ game.cmd_name }}_imports() {
  # Self destruct on first run
  unset -f $FUNCNAME

  for import in $@; do
    __gs_source_file "${import##*/}" "${import%/*}"
  done
}
__gs_{{ game.cmd_name }}_imports {{ game.imports | join(' ') }}

# Provide rendered user-facing game command
{{ game.cmd_name }}() {
  {% if game.min_bash %}
  __gs_bash_ver_check {{ game.min_bash }} || {
    __gs_errormsg "$FUNCNAME requires bash >= {{ game.min_bash }} to run"
    return 1
  }
  {% endif %}
  __gs_setdebug $1 || shift

  if [[ "${GS_API_KEY:-null}" == "null" && "$1" != "login" ]]; then
    __gs_errormsg "Please log in to the game server with \`${FUNCNAME[-1]} login\` to continue."
    __gs_errormsg "If logging in for the first time, input desired password to login prompt."
    return 1
  fi

  #TODO: add getopt parsing for --quiet, --help, etc
  case _$1_ in
    {% if game.has_main %}
    _play_) : Play the game
      #TODO: loading msg here
      echo I\'m playing {{ game.full_name }}!
      __gs_{{ game.cmd_name }}_main
    ;;
    {% endif %}
    _help_) : Open {{ game.cmd_name }} help
      #TODO: man pages for games
      __gs_doccer
    ;;
    #TODO: add update specific handling to init latest game version as well
    *)
      # Pass to default_cmd if option not supported here
      # This allows easy login/logout/passwd/update/help for all cmds with default_cmd == "game"
      if declare -f {{ game.default_cmd.split(' ')[0] }} &>/dev/null; then
        {{ game.default_cmd }} "$@"
      else
        __gs_errormsg "Option $1 not found."
        __gs_infomsg "Run \`${FUNCNAME[-1]} help\` for help!"
        return 1
      fi
    ;;
  esac
}
__gs_source_template {{ game.cmd_name }}-completion

