#!/usr/bin/env bash

## templates/engine/game-common ##
## This template provides common files and functionality needed for most games
##
## Adding this as an import sources common game imports and defines useful common
##   functions for games to use
## This file is a helpful resource on common procedure for games that might only
##   need to do some of the steps for whatever reason
##
## Functions:
##   __gs_GAME_common (init|deinit) - easy function to init/deinit a game
##                                    provides one fxn call for game setup/teardown
##
## Configurable elements to __gs_GAME_common:
##   mouse: games can add "mouse: true" to their cfg to optionally enable mouse
##            input while inited
##
## This sources a default demo game (templates/engine/game-demo) to enable games
##   being playable in a demo example state after just a directory being created
##
## Author: Daniel Tucker <github.com/Vision940>
##

__gs_source_common() {
  # Self destruct on first run
  unset -f $FUNCNAME

  local __GS_COMMON=(
    games/{{ game.source_name }}-utils
    static/engine/{graphics,cache,streams,input,events,term,nodes,scenes}
  )

  local import
  for import in ${__GS_COMMON[@]}; do
    __gs_source_file "${import##*/}" "${import%/*}"
  done
}
__gs_source_common

__gs_{{ game.cmd_name }}_common() {
  local action="$1"
  __gs_required_args action || return 2

  case _${action}_ in
    _init_)
      # Get game name and exit tracker into environment
      GS_GAME={{ game.cmd_name }}
      GS_EXIT=false
      # Cache init is first because sprites and term need it
      __gs_cache init {{ game.cmd_name }} || return 1
      # Load sprites to cache dir for game
      __gs_cache load-sprites {{ game.cmd_name }} || return 1
      # Init term for game
      __gs_{{ game.cmd_name }}_term init || return 1
      # Set up term env variables for game
      __gs_{{ game.cmd_name }}_term env || return 1
      # Init keyboard handler
      __gs_keyboard init || return 1
      {% if game.mouse %}
      # Init mouse handler after keyboard
      __gs_mouse init || return 1
      {% endif %}
      # Set up event env
      __gs_event setup
      # Set up scene env
      __gs_scene_manager setup
      # Set up node/widget envs
      __gs_node_manager setup
      # Set up frame env
      __gs_frame setup
    ;;
    _deinit_)
      # Remove game name and exit tracker from env
      unset GS_GAME GS_EXIT
      # __gs_GAME_term's RETURN trap runs __gs_term deinit so that is omitted here
      # __gs_term deinit deinits mouse, so that is also omitted
      # Close keyboard handler - must be before deinit cache
      __gs_keyboard deinit-stream
      # Remove entire game cache
      __gs_cache deinit
      # Clean up event env
      __gs_event cleanup
      # Clean up scene env
      __gs_scene_manager cleanup
      # Clean up node env
      __gs_node_manager cleanup
      # Clean up frame env
      __gs_frame cleanup
      #TODO: Unset game-specific funcs from prefixes
      # Untrap keyboard ^C trap as final action
      __gs_keyboard deinit-trap
    ;;
  esac
}

__gs_source_games {{ game.source_name }}-demo

