#!/usr/bin/env bash
#
# Frontend for the "readbmp" library that prints a bitmap image to the terminal
# using the half-block character.
#
# Author: Ponali <ponali2k@gmail.com>
# Date: September 02, 2025
# License: MIT

. ./dev/lib/readbmp || exit

debug() {
	echo '[debug]' "$@" >&2
}

fatal() {
	echo '[fatal]' "$@" >&2
	exit 1
}

print_half_blocks() {
    for ((y = 0; y < bitmap_height; y+=2)); do
        local prev_ansi=""
        for ((x = 0; x < bitmap_width; x++)); do
            local color1=( ${ get_bitmap_pixel $x $y; } )
            local color2=( ${ get_bitmap_pixel $x $((y+1)); } )
            local color3=( ${ get_bitmap_pixel $((x+1)) $y; } )
            local color4=( ${ get_bitmap_pixel $((x+1)) $((y+1)); } )

            local ansi=""
            if (( ${color1[3]} == 1 )); then
              ansi+="esc[48;2;${color1[0]};${color1[1]};${color1[2]}m"
            fi
            if (( ${color2[3]} == 1 )); then
              ansi+="esc[38;2;${color2[0]};${color2[1]};${color2[2]}m"
            fi

            local next_ansi=""
            if (( ${color3[3]} == 1 )); then
              next_ansi+="esc[48;2;${color3[0]};${color3[1]};${color3[2]}m"
            fi
            if (( ${color4[3]} == 1 )); then
              next_ansi+="esc[38;2;${color4[0]};${color4[1]};${color4[2]}m"
            fi

            local suffix=""
            local prefix="$ansi"
            if [[ "$next_ansi" != "$ansi" ]]; then
                suffix="esc[0m"
            fi
            if [[ "$prev_ansi" == "$ansi" ]]; then
                prefix=""
            fi

            # Full reset if not opaque
            local char="▄"
            if (( ${color1[3]} == 0 || ${color2[3]} == 0 )); then
              ansi=""
              char=" "
              prefix=""
              suffix=""
            fi

            printf "%s" "${prefix//esc/$'\x1b'}${char}${suffix//esc/$'\x1b'}"
            prev_ansi="$ansi"
        done
        echo # Newline
    done
}

main() {
  local file=in.bmp
  local automated=false

  local OPTIND OPTARG opt
	while getopts 'i:a' opt; do
		case "$opt" in
			i) file=$OPTARG;;
      a) automated=true;;
			*) fatal 'bad option';;
		esac
  done

  if [ ! -f "$file" ]; then
      fatal "file not found: $file"
  fi

  $automated || echo -ne "\e[s" # save cursor position
  read_bmp < "$file"
  $automated || echo -ne "\e[u\e[J" # restore cursor position and remove all debug logs

  print_half_blocks

  $automated || echo -ne "\e[0m"
}

main "$@"
