#!/usr/bin/env bash

## static/client/functions/docs ##
## Provides functions relating to gameserver documentation
##
## Functions:
##   __gs_doccer
##     function that opens server man page from URL/man/CALLER.1
##   __gs_longopts OPTS
##     function to allow compatibility with -h|--help and --version convention
##     call at beginning of user-facing function as `__gs_longopts "$@" && return`
##     for games with more to add to the copyright line, set GS_<GAME>_COPYRIGHT
##       and it will be added to `<GAME> --version`
##     the version string used is stored in GS_<GAME>_VER, but defaults to
##       GS_SERVER_VER as set in initial source if <GAME> version unset/null
##   __gs_unfound_option OPTION
##     prints standardized option not found message for passed in OPTION
##     if OPTION is empty, just says to run `FUNC help` for help
##
## Author: Daniel Tucker <github.com/Vision940>
##

__gs_doccer() {
  # Pre-4.2 need to call with caller name bc no negative indexing
  local caller=${1:-${FUNCNAME[-1]}}
  local manpage
  manpage="$(curl -sfL "$GS_URL/man/${caller}.1")" || {
    __gs_errormsg "Could not open man page for $caller"
    return 1
  }

  printf '%s' "$manpage" | groff -Tutf8 -man | less -RF || {
    __gs_errormsg "Could not render man page for $caller"
    return 1
  }
}

__gs_longopts() {
  # Get length of FUNCNAME to support pre-4.2
  # This is so a theoretical pre-4.2 cmd line game could still call __gs_longopts
  local funcStackLastIdx=$((${#FUNCNAME[@]}-1))
  local caller=${FUNCNAME[$funcStackLastIdx]//-/_}
  local verVar="GS_${caller^^}_VER"
  local version="${!verVar:-$GS_SERVER_VER}"
  local copyrightVar="GS_${caller^^}_COPYRIGHT"
  local parsed
  parsed=$(getopt -aU -o h,v -l help,version -n "$caller" -- "$@" 2>/dev/null) || {
    local params=" $* "
    if [[ "$params" =~ " "(--version|--help|-h)" " ]]; then
      parsed="${BASH_REMATCH[1]}" 2>/dev/null || return 1
    else
      return 1
    fi
  }

  eval "set -- $parsed"
  while (($#)); do
    case $1 in
      '-v') break ;; # preserve this for debug
      '--version')
        command cat <<- EOF
					$caller (gameserver) v$version
					Copyright (C) 2026 Daniel Tucker <github.com/Vision940>
					${!copyrightVar:+${!copyrightVar}
          }
					License MIT
				EOF
        return 0
      ;;
      '-h'|'--help')
        __gs_doccer $caller
        return 0
      ;;
      '--') break ;;
    esac
    shift
  done
  return 1
}

__gs_unfound_option() {
  (($#)) && __gs_errormsg "Option $@ not found."
  __gs_infomsg "Run \`${FUNCNAME[-1]} help\` for help!"
}

