#!/usr/bin/env bash

## static/client/functions/fetcher ##
## Provides functions to fetch code from server
##
## Functions:
##   __gs_source_template PATH
##     function to source rendered templates from server at PATH
##   __gs_source_games GAME
##     function to source a game from the static/games path
##   __gs_module_selfdestruct MODULE ROUTE
##     function to dynamically unset all functions provided by MODULE at ROUTE on server
##     default ROUTE is static/client
##
##   __gs_source_file isn't here because it is needed in init
##
## Author: Daniel Tucker <github.com/Vision940>
##

# __gs_source_template PATH
__gs_source_template() {
  __gs_source_file "$1" templates
}

__gs_source_games() {
  __gs_source_file "$1" games
}

# __gs_module_selfdestruct MODULE ROUTE
__gs_module_selfdestruct() {
  local serverPath=${2:-static/client}
  local fxns="$(sed -ne 's/^\(__gs_[^(]\+\)() {$/\1/p' <(curl -sfL $GS_URL/$serverPath/$1))"
  unset -f $fxns
}

#TODO: __gs_load_game_lib that loads a game's libraries/sprite files to /tmp cache

