#!/usr/bin/env bash

## static/client/functions/messenger ##
## Provides functions to interact with server
##
## Functions:
##   __gs_json_content [KEY VAL [KEY VAL [...]]]
##     function that formats input keys/vals as a json string
##     calling with KEY1 VAL1 KEY2 VAL2 prints '"KEY1": "VAL1", "KEY2": "VAL2"'
##   __gs_curl_post ROUTE [KEY VAL [KEY VAL [...]]]
##     function that curls server with POST request to URL/ROUTE
##     uses KEY/VAL pairs entered to call __gs_json_content and adds result to msg
##     by default adds user/key/ver to every message
##     this function is the preferred way to interact with the server
##   __gs_parse_response JQCODE RESP [FILTEROFF]
##     function that executes JQCODE on RESP string
##     if FILTEROFF is populated, will parse responses without "valid": true
##     calls `jq -r "JQCODE" <<<"RESP"` and prints result
##   __gs_check_version RESP
##     parses json RESP string for oldver key found when server api version is old
##     prints warning and returns 1 if version is old
##     server will not comply with requests if version is old
##   __gs_response_valid RESP
##     checks json RESP string for '"valid": true'
##     server should include valid bool flag in every response
##     returns 1 if valid is missing or not true
##   __gs_request REQ [OPTS]
##     function to handle common game requests/responses
##     supported REQ values and their OPTS:
##       _apikey_: gets api key from server if able
##       _login_ PASSWD: logs in to server and handles possible errors
##                       allows users to set password on first login
##
## Author: Daniel Tucker <github.com/Vision940>
##

__gs_json_content() {
  local arg
  local jsonContent=""

  if (( $# % 2 == 1 )); then
    return 1
  fi

  for (( arg=1 ; arg<=$# ; arg++ )); do
    if (( arg % 2 == 1 )); then
      jsonContent+="\"${!arg}\": "
    else
      jsonContent+="\"${!arg}\", "
    fi
  done
  echo "${jsonContent%, }"
}

# __gs_curl_post ROUTE [KEY VAL [KEY VAL [...]]]
__gs_curl_post() {
  local route="$1"
  local jsonContent=""

  jsonContent="$(__gs_json_content ${@:2})" || return 1
  # Add these to all messages
  jsonContent+="${jsonContent:+, }\"user\": \"$GS_USER\", \"key\": \"$GS_API_KEY\", \"ver\": \"$GS_SERVER_API_VER\""

  __gs_debugmsg "Requesting $GS_URL/$route with {$jsonContent}" 2
  __gs_debugmsg "curl -L -m 5 -X POST -H \"Content-Type: application/json\" -d \"{${jsonContent//\"/\\\"}}\" $GS_URL/$route" 3
  local response=$(curl -sL -m 5 -X POST -H "Content-Type: application/json" -d "{$jsonContent}" $GS_URL/$route)
  __gs_debugmsg "resp: $response" 2
  __gs_check_version "$response"
  printf "%s" "$response"
}

# __gs_parse_response JQCODE RESP [FILTEROFF]
__gs_parse_response() {
  local keyStr="$1"
  local jsonResp="$2"
  local filterOff="${3:-}" # Off if 3rd arg present

  # Filters for responses with valid: true
  if [[ -n "$filterOff" ]] || __gs_response_valid "$jsonResp"; then
    jq -r "$keyStr" <<<"$jsonResp"
  fi
}

__gs_check_version() {
  local jsonResp="$1"
  if jq -e ".oldver == true" <<<"$jsonResp" &>/dev/null; then
    __gs_errormsg "Old server api version detected."
    __gs_errormsg "Please run \`game update\` to get the latest server updates!"
    return 1
  fi
}

__gs_response_valid() {
  local jsonResp="$1"
  jq -e ".valid == true" <<<"$jsonResp" &>/dev/null && return 0
  return 1
}

__gs_request() {
  __gs_debugmsg "Attempting to send $1 request"
  case _$1_ in
    __apikey__)
      local response=$(__gs_curl_post user)
      __gs_parse_response ".key" "$response"
    ;;
    __login__)
      local response=$(__gs_curl_post login password $2) || return 1
      if __gs_response_valid "$response"; then
        GS_API_KEY=$(__gs_parse_response ".key" "$response") || return 1
        __gs_infomsg "Successfully logged in $GS_USER!"
        return 0
      else
        local action=$(__gs_parse_response ".action" "$response" off) || return 1
        __gs_debugmsg "Action needed: $action"
        case "${action// /}" in
          Setpassword)
            __gs_set_passwd $2 || return 1
          ;;
          Retrypassword)
            __gs_errormsg "Incorrect password to login. Please try again or ask an administrator to reset it."
          ;;
          Invaliduser)
            # Should hopefully never get here
            __gs_errormsg "User $GS_USER is not a user on the server. Please contact an administrator for assistance." fatal
          ;;
        esac

        return 1
      fi
    ;;
  esac
}

