#!/usr/bin/env bash

## static/client/functions/utility ##
## Provides utility functions for other functions
##
## Functions:
##   __gs_required_args [-ndvq] [ARG ARG ...]
##     function to check if ARG names are set in env
##     opts:
##       -n  ARG is an env var that should be set
##       -d  just print as debug if ARG unset
##       -v  just check if var exists with `declare -p`
##       -q  don't log non-existence
##     otherwise, prints error saying required arg ARG not set in fxn
##     returns non-zero on first ARG unset
##   __gs_required_fxn FXN-NAME
##     checks for function FXN-NAME in env and returns non-zero with
##       error msg if missing
##   __gs_trap_check SIGNAL
##     function to check if SIGNAL is a trap in the current env
##     returns non-zero if SIGNAL is trapped
##   __gs_bash_vercheck VERSION="MAJOR.MINOR"
##     function to check if current bash version is >= VERSION
##     returns 0 if >= VERSION
##     this is here as a preliminary check to avoid weird term states
##     still expect to catch misisng newer bash features with ||
##   __gs_unset_vars_from_prefixes PREFIX [PREFIX ...]
##     find all vars in env starting with each PREFIX and unset them all
##     useful to clean up env after function runs
##
## Author: Daniel Tucker <github.com/Vision940>
##

__gs_required_args() {
  local isArg=true
  local vague=false
  local logger=__gs_errormsg
  local opt OPTIND OPTARG
  while getopts 'ndvq' opt; do
    case "$opt" in
      d) logger=__gs_debugmsg ;;
      n) isArg=false ;;
      v) vague=true ;;
      q) logger=: ;;
      *) __gs_errormsg "Unrecognized option to required args"; return 2 ;;
    esac
  done
  shift $(( OPTIND - 1 ))

  local arg
  for arg in $@; do
    if $vague; then
      __gs_debugmsg "Checking $($isArg && echo "required arg" || echo "env var") $arg to ${FUNCNAME[1]} is declared" 4
      declare -p $arg &>/dev/null || {
        $logger "Missing $($isArg && echo "required arg" || echo "env var") $arg to ${FUNCNAME[1]}"
        return 1
      }
    else
      __gs_debugmsg "Checking $($isArg && echo "required arg" || echo "env var") $arg to ${FUNCNAME[1]} has value - \"${!arg}\"" 4
      [[ -z "${!arg}" ]] && {
        $logger "Missing $($isArg && echo "required arg" || echo "env var") $arg to ${FUNCNAME[1]}"
        return 2
      }
    fi
  done

  return 0
}

__gs_required_fxn() {
  local fxnName="$1"
  __gs_required_args fxnName || return 2
  declare -f "$fxnName" &>/dev/null || {
    __gs_errormsg "Missing $fxnName function required to ${FUNCNAME[1]}"
    return 1
  }
  return 0
}

__gs_trap_check() {
  local trapTxt="$(trap -p $1)"

  [[ "$trapTxt" =~ ^trap\ --\ \'(.*)\'\ $1$ ]] && {
    __gs_errormsg "Attempted to trap $1 when signal already trapped to '${BASH_REMATCH[1]}'"
    return 1
  }

  return 0
}

__gs_bash_ver_check() {
  local version="$1"
  __gs_required_args version

  [[ "$version" =~ ^[0-9]"."[0-9]$ ]] || {
    __gs_errormsg "Unexpected version string format passed to $FUNCNAME"
    return 2
  }

  local major=${version%\.*}
  local minor=${version#*\.}

  # Return 0 if >= version passed in
  (( BASH_VERSINFO[0] > $major || (BASH_VERSINFO[0] == $major && BASH_VERSINFO[1] >= $minor) ))
}

__gs_unset_vars_from_prefixes() {
  (($#)) || return 2

  local prefix name
  for prefix in $@; do
    while IFS= read -r name; do
      unset "$name"
    done < <(compgen -v "$prefix")
  done
}

#TODO: Unset funcs from prefixes

