#!/usr/bin/env bash

## static/client/game ##
## This file provides the game function to gameserver users and imports
##   necessary functions from the server for game to run correctly
##
## Imports:
##   cmdenv - sourced here but used in games for terminal-style text input
##   tput - tput wrapper to speed up drawing in all games using ANSI esc codes
##   docs - renders man help pages for gameserver suite
##   fetcher - functions to fetch code from server
##   logging - functions that enable consistent info/warn/debug/error messages server-wide
##   math - functions to enable floating point arithmetic using bash builtins
##   messenger - functions to enable server messaging for logins/version checking/api keys
##   output - functions to pretty print common server output types
##   prompts - functions to simplify cmd line user prompting
##   utility - functions to simplify other functions
##
## Functions:
##   game [OPTS]
##     the game command is the core client entrypoint to server capability
##     see `game help` for more detailed description of OPTS
##
## Author: Daniel Tucker <github.com/Vision940>
##

__GS_IMPORTS=(
  sources/cmdenv/cmdenv
  sources/tput/tput
  functions/{docs,fetcher,logging,math,messenger,output,prompts,utility}
)

for import in ${__GS_IMPORTS[@]}; do
  __gs_source_file $import
done
unset import __GS_IMPORTS

game() {
  __gs_longopts "$@" && return
  __gs_setdebug $1 || shift

  if [[ "${GS_API_KEY:-null}" == "null" && "$1" != "login" ]]; then
    __gs_errormsg "Please log in to the game server with \`${FUNCNAME[-1]} login\` to continue."
    __gs_errormsg "If logging in for the first time, input desired password to login prompt."
    return 1
  fi

  local resp
  case _$1_ in
    # User-facing functionality
    _account_) : View account info
      resp=$(__gs_curl_post api/user msgType whoami) || return 1
      __gs_json_to_table \
        -d "userProfile" \
        -j "$resp" \
        Username:username Status:status "Last Seen:last_seen_at"
    ;;
    _admin_) : View admin info
      __gs_required_fxns __gs_admin || return 1
      __gs_admin "${@:2}"
    ;;
    _login_) : Log into the server
      __gs_infomsg "Logging in $GS_USER..."
      __gs_infomsg "To change users, run \`gameinit -u USERNAME\`"

      # Check if user is already logged in
      __gs_logged_in && {
        __gs_errormsg "$GS_USER is already logged in";
        __gs_errormsg "Run \`${FUNCNAME[-1]} logout\` to log out."
        return
      }

      # Try to refresh api key if client is out of date
      __gs_request _apikey_ || return 1
      __gs_logged_in && {
        __gs_infomsg "Successfully logged in $GS_USER!"
        return 0
      }

      __gs_source_file functions/userctl || return 1

      # Get password
      local hashedPassword
      hashedPassword=$(__gs_passwd_prompt) || { __gs_userctl_cleanup; return 1; }
      echo

      # Login with password
      __gs_request _login_ "$hashedPassword" || { __gs_userctl_cleanup; return 1; }

      # Grab correct __gs_admin function
      source <(__gs_curl_post -q api/admin msgType query)

      # Cleanup
      __gs_userctl_cleanup
    ;;
    _logout_) : Log out of the server
      __gs_api_key remove
      __gs_infomsg "Successfully logged out $GS_USER!"
    ;;
    _passwd_) : Change server password
      __gs_source_file functions/userctl || return 1

      local password hashedPassword
      unset GS_API_KEY
      __gs_infomsg "Changing password for $GS_USER..."
      hashedPassword=$(__gs_passwd_prompt current) || { __gs_userctl_cleanup; return 1; }
      echo

      __gs_request _login_ $hashedPassword || { __gs_userctl_cleanup; return 1; }
      if __gs_logged_in; then
        hashedPassword=$(__gs_passwd_prompt new) || { __gs_userctl_cleanup; return 1; }
        echo
        __gs_set_passwd $hashedPassword || { __gs_userctl_cleanup; return 1; }
      else
        __gs_errormsg "Could not log in with existing password."
      fi

      __gs_userctl_cleanup
    ;;
    _update_) : Get latest version of game
      # Refresh self
      local curver="$GS_SERVER_VER"
      __gs_infomsg "Grabbing latest update from server..."
      source <(curl -sfL $GS_URL) -u $GS_USER
      if [[ "$curver" != "$GS_SERVER_VER" ]]; then
        __gs_infomsg "Done!"
      else
        __gs_warnmsg "No new changes detected."
      fi
    ;;
    _users_) : See user info
      resp=$(__gs_curl_post api/user msgType list) || return 1
      if jq -e ".admin == true" <<<"$resp" &>/dev/null; then
        __gs_json_to_table \
          -d "users" -a \
          -j "$resp" \
          ID:id Username:username Status:status "Status By:status_by" \
          "Status Reason:status_reason" "Status Time:status_at" \
          "Last Seen:last_seen_at"
      else
        __gs_json_to_table \
          -d "users" -a \
          -j "$resp" \
          Username:username Status:status "Last Seen:last_seen_at"
      fi
    ;;
    _help_) : Open game help
      __gs_doccer
    ;;
    __) __gs_unfound_option ;;
    *) __gs_unfound_option "$1" ;;
  esac
}
__gs_source_template game-completion

# Grab game launcher functions
__gs_source_games

