#!/usr/bin/env bash

## templates/client/games ##
## Lightweight client template to create placeholder game functions
##
## Idea here is we don't want to flood client envs with functions/env vars/etc
##   that they might not use
## Instead, we create self-destructing placeholder functions that fetch the
##   latest version of the relevant game when run
## This way, client users can run a specific game command on source, but they
##   don't have to have their environments flooded with gameserver code
##
## This provides a function for every game in the game list, currently:
##   - {{ game_list | join('\n##   - ') }}
##
## Author: Daniel Tucker <github.com/Vision940>
##

GS_GAME_LIST="{{ game_list | map(attribute='cmd_name') | list | join(' ') }}"

{% for game in game_list %}
{{ game.cmd_name }}() {
  local opt OPTIND OPTARG logger=__gs_infomsg
  while getopts ':q' opt; do
    case "$opt" in
      q) logger=__gs_debugmsg ;;
      *) ((OPTIND--)); break ;;
    esac
  done
  shift $(( OPTIND - 1 ))

  $logger "Loading latest version of {{ game.cmd_name }} from server..."
  unset -f {{ game.cmd_name }} # Unset placeholder function (this)
  __gs_source_games {{ game.source_name }} # Set up real function
  command -v {{ game.cmd_name }} &>/dev/null && {{ game.cmd_name }} $@
}
{% endfor %}

